### ISSUE TITLE
Account query not working properly

### ISSUE THREAD

**Issue by diyahir** [Mirror-Protocol/mirror-graph#12]
I tried querying several accounts and the terra finder account balance is always significantly different than the balances shown here in the graphql 

Below is one such example. Generally, the query balances is always null.
https://finder.terra.money/columbus-4/address/terra1ljxeqeqe95kcnd54sw3q7wmt0we5tdnc3gyw7j

query {
  account(address: "terra1ljxeqeqe95kcnd54sw3q7wmt0we5tdnc3gyw7j") {
    address
    haveBalanceHistory
    balances {
      token
      averagePrice
    }
    accumulatedGovReward
    voteHistory {
      pollId
      amount
    }
  }
}

<img width="1406" alt="Screen Shot 2021-06-28 at 17 14 02" src="https://user-images.githubusercontent.com/32445955/123710424-6176b280-d834-11eb-8304-f69c612c67b6.png">

<img width="1338" alt="Screen Shot 2021-06-28 at 17 14 16" src="https://user-images.githubusercontent.com/32445955/123710453-70f5fb80-d834-11eb-8f1e-9410ef40f26c.png">

**Comment by mesyakim** [comment]
@diyahir 
1. balances is not account query's field. you can query balances like this:
`query {
  balances(address: "terra1ljxeqeqe95kcnd54sw3q7wmt0we5tdnc3gyw7j") {
    token
    averagePrice
  }
}
`

2. If there is a short farm transaction, a bug has been found that the balance is not reflected. It will be fixed tomorrow.
