### ISSUE TITLE
CDP Does Not Accept Array of Addresses

### ISSUE THREAD

**Issue by cjbeery24** [Mirror-Protocol/mirror-graph#13]
Is it possible to make the CDP resolver accept an array of addresses instead of just a single address?

**Comment by hanjukim** [comment]
@mesyakim @ALPAC-4 Is it possible?

**Comment by mesyakim** [comment]
> Is it possible to make the CDP resolver accept an array of addresses instead of just a single address?

@cjbeery24 Yes, it is possible with array length limit. For what purpose do you need it?

**Comment by cjbeery24** [comment]
It would be nice to be able to check the status of CDP for multiple addresses without burdening the API with multiple requests.

**Comment by mesyakim** [comment]
@cjbeery24 It will be updated soon.

**Comment by mesyakim** [comment]
@cjbeery24 check this commit > https://github.com/Mirror-Protocol/mirror-graph/commit/0ea511480916f80c8d7fb7146358c9141160fd1a
