### ISSUE TITLE
Is there any example of config files.

### ISSUE THREAD

**Issue by narawit0** [Mirror-Protocol/mirror-graph#9]
Can I have some example of these files 

.envrc on project root
address.json, assets.json, codeIds.json, contracts.json, description.json on project root/data

**Comment by qrk12** [comment]
+1
ormconfig.json on project root

**Comment by shahzaibatzeeyotech** [comment]
> +1
> ormconfig.json on project root

please check docs of typeORM  from here

https://typeorm.io/#/using-ormconfig

**Comment by shahzaibatzeeyotech** [comment]
> Can I have some example of these files
> 
> .envrc on project root
> address.json, assets.json, codeIds.json, contracts.json, description.json on project root/data

you can find interfaces  of json files structure from src/types/data.ts file.

view these two files for solution:

1=src/lib/data.ts
2=src/types/data.ts
